//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtworkDatabase.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paint
    {
        public int ID { get; set; }
        public string PaintingTitle { get; set; }
        public Nullable<System.DateTime> Years { get; set; }
        public string ArtistName { get; set; }
        public string Direction { get; set; }
    }
}
